### ISSUE TITLE
View [builder_root] not found

### ISSUE THREAD

**Issue by thomaswacker** [allamo123/laravel-grapes#10]
Tried in linux. When i call the front-end-builder url, I get the error message

"View [builder_root] not found"

I think, the directory "Views" in resources path should be lower case. I temporary fixed this on my local installation to lower case, and its working now.

**Comment by allamo123** [comment]
Hello, @thomaswacker,

It's working fine from my side I require the package on new project and it work fine, please share the code for the issue.

Thanks

**Comment by Sarthakj02** [comment]
@allamo123  yes i also faced same issue in linux because in linux folder name are case sensitive and in windows / mac it is not case sensitive . when we publish LaravelGrapesServiceProvider Views folder will not be published in linux due to this line
`$this->loadViewsFrom(__DIR__.'/../resources/views', 'lg');` 
views lower case but in package folder name is Views as shared in screenshot. you should fix it or i can even submit pr
![image](https://user-images.githubusercontent.com/108919895/216612536-d861ced1-87f1-4192-babe-216931228bb3.png)

**Comment by Gagandeep188** [comment]
@allamo123 sir its not updated yet geting same error please update: the folder name capital Views to views into vendor/msa/laravel-grapes/resources/

**Comment by Sarthakj02** [comment]
@Gagandeep188  try deleting vendor folder and run composer install it will update vendor code
